# Generated by Django 3.1.2 on 2020-11-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userobject',
            name='id',
        ),
        migrations.AlterField(
            model_name='userobject',
            name='user_token',
            field=models.CharField(editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
